services:
  aladin-sp:
    build: .
    container_name: aladin-sp
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - aladinsp-memcached
      - aladinsp-mariadb
    networks:
      - proxy

  aladinsp-nginx:
    image: nginx
    container_name: aladinsp-nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aladinsp-nginx.rule=Host(`simplesamlphp.wrlc.localhost`)"
      - "traefik.http.routers.aladinsp-nginx.tls=true"
      - "traefik.http.routers.aladinsp-nginx.entrypoints=websecure"
    volumes:
      - ./:/app
      - ./aladin-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - aladin-sp
    networks:
      - proxy

  aladinsp-memcached:
    image: memcached:latest
    container_name: aladinsp-memcached
    networks:
      - proxy

  aladinsp-mariadb:
    image: mariadb:10.5.12
    container_name: aladinsp-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saml
      MYSQL_USER: simplesamlphp
      MYSQL_PASSWORD: user
    ports:
      - "3325:3306"
    volumes:
      - aladinsp_mariadb_data:/var/lib/mysql
    networks:
      - proxy

volumes:
    aladinsp_mariadb_data:

networks:
    proxy:
        external: true