# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.svc_provider: '%env(SERVICE_PROVIDER_NAME)%'
    app.authz_url: '%env(PATRON_AUTHORIZATION_URL)%'
    app.cookie_prefix: '%env(COOKIE_PREFIX)%'
    app.cookie_domain: '%env(COOKIE_DOMAIN)%'
    app.memcached_host: '%env(MEMCACHED_HOST)%'
    app.memcached_port: '%env(MEMCACHED_PORT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $svcProvider: '%app.svc_provider%'
            $authzUrl: '%app.authz_url%'
            $cookiePrefix: '%app.cookie_prefix%'
            $cookieDomain: '%app.cookie_domain%'
            $memcachedHost: '%app.memcached_host%'
            $memcachedPort: '%app.memcached_port%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones