name: Test

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.5.12
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: saml
          MYSQL_USER: simplesamlphp
          MYSQL_PASSWORD: user
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
        - uses: actions/checkout@v3
        - uses: php-actions/composer@v6
        - run: vendor/bin/phpunit